/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moose.views.modals;

import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;
import moose.Main;
import moose.objects.ImageSearchResponse;
import moose.services.AlbumArtFinderService;
import moose.utilities.Logger;
import moose.utilities.Utils;

/**
 *
 * @author pat
 */
public class AlbumArtFinderFrame extends javax.swing.JFrame {

    Logger logger = Main.logger;

    List<Icon> icons = new ArrayList<>();
    int currentIconIndex;

    SwingWorker<Void, Void> // make a swing worker do the image search in a separate thread so I can update the GUI
            worker = new SwingWorker<Void, Void>() {
        @Override
        protected Void doInBackground() throws Exception {
            // reset UI

            String query = queryTextField.getText();
            responses = AlbumArtFinderService.getImages(query);

            icons = getIconsFromImages(responses);
            if (icons.size() > 1) {
                albumArtImageLabel.setIcon(icons.get(0));
                currentIconIndex = 0;
                nextButton.setEnabled(true);
                prevButton.setEnabled(false);
            } else if (icons.size() == 1) {
                albumArtImageLabel.setIcon(icons.get(0));
                currentIconIndex = 0;
                nextButton.setEnabled(false);
                prevButton.setEnabled(false);
            } else if (icons.isEmpty()) {
                albumArtImageLabel.setIcon(null);
                currentIconIndex = -1;
                nextButton.setEnabled(false);
                prevButton.setEnabled(false);
                statusLabel.setText("No results found!");
                loadingLabel.setIcon(null);
                searchButton.setText("Search");
                return null;
            }

            statusLabel.setText("Result 1 of " + responses.size());
            sourceLabel.setText(responses.get(currentIconIndex).getLink());
            sourceLabel.setToolTipText(responses.get(currentIconIndex).getLink());
            sizeLabel.setText(responses.get(currentIconIndex).getBImage().getWidth() + "x" + responses.get(currentIconIndex).getBImage().getHeight());
            loadingLabel.setIcon(null);
            confirmButton.setEnabled(true);
            googleImagesButton.setEnabled(true);

            return null;    // don't return anything since we're just playing with threads
        }
    };

    List<ImageSearchResponse> responses;
    BufferedImage foundCover;
    File dir;
    List<Integer> rows;

    /**
     * Creates new form AlbumArtFinderFrame
     *
     * @param albumInfo
     * @param dir
     * @param rows
     */
    public AlbumArtFinderFrame(String albumInfo, File dir, List<Integer> rows) {
        initComponents();
        headerLabel.setText("Finding album art for \"" + albumInfo + "\"");
        queryTextField.setText(albumInfo);
        queryTextField.requestFocus();
        queryTextField.selectAll();
        this.dir = dir;
        this.rows = rows;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        queryTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        albumArtImageLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        googleImagesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sourceLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        loadingLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Album Art Finder");
        setAlwaysOnTop(true);
        setResizable(false);

        L1.setText("Search Query:");

        queryTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                queryTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                queryTextFieldKeyReleased(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.setEnabled(false);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        albumArtImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        albumArtImageLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        albumArtImageLabel.setMaximumSize(new java.awt.Dimension(250, 250));
        albumArtImageLabel.setMinimumSize(new java.awt.Dimension(250, 250));
        albumArtImageLabel.setSize(new java.awt.Dimension(153, 153));

        nextButton.setText(">");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        prevButton.setText("<");
        prevButton.setEnabled(false);
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        googleImagesButton.setText("Open Google Images");
        googleImagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                googleImagesButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Source:");

        jLabel2.setText("Size:");

        sourceLabel.setMaximumSize(new java.awt.Dimension(310, 16));
        sourceLabel.setMinimumSize(new java.awt.Dimension(310, 16));
        sourceLabel.setSize(new java.awt.Dimension(310, 16));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(L1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(queryTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(googleImagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(prevButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(nextButton))
                                            .addComponent(confirmButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sourceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(albumArtImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(queryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(sourceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(albumArtImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(confirmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextButton)
                            .addComponent(prevButton)))
                    .addComponent(googleImagesButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        confirmImage();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void queryTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryTextFieldKeyReleased
        if (queryTextField.getText().equals("")) {
            confirmButton.setEnabled(false);
        } else {
            confirmButton.setEnabled(true);
        }
    }//GEN-LAST:event_queryTextFieldKeyReleased

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (currentIconIndex < icons.size() - 1) {
            currentIconIndex++;
            albumArtImageLabel.setIcon(icons.get(currentIconIndex));
            prevButton.setEnabled(true);

            if (currentIconIndex == icons.size() - 1) {
                nextButton.setEnabled(false);
                prevButton.setEnabled(true);
            }
        }

        sourceLabel.setText(responses.get(currentIconIndex).getLink());
        sourceLabel.setToolTipText(responses.get(currentIconIndex).getLink());
        sizeLabel.setText(responses.get(currentIconIndex).getBImage().getWidth() + "x" + responses.get(currentIconIndex).getBImage().getHeight());
        statusLabel.setText("Result " + (currentIconIndex + 1) + " of " + responses.size());
    }//GEN-LAST:event_nextButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        if (currentIconIndex > 0) {
            currentIconIndex--;
            albumArtImageLabel.setIcon(icons.get(currentIconIndex));
            nextButton.setEnabled(true);

            if (currentIconIndex == 0) {
                prevButton.setEnabled(false);
                nextButton.setEnabled(true);
            }
        }

        sourceLabel.setText(responses.get(currentIconIndex).getLink());
        sourceLabel.setToolTipText(responses.get(currentIconIndex).getLink());
        sizeLabel.setText(responses.get(currentIconIndex).getBImage().getWidth() + "x" + responses.get(currentIconIndex).getBImage().getHeight());
        statusLabel.setText("Result " + (currentIconIndex + 1) + " of " + responses.size());
    }//GEN-LAST:event_prevButtonActionPerformed

    private void googleImagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_googleImagesButtonActionPerformed
        Utils.openPage(AlbumArtFinderService.buildImageSearchQuery(queryTextField.getText()));
        this.dispose();
    }//GEN-LAST:event_googleImagesButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (searchButton.getText().equals("Search")) {
            doSearch();
        } else if (searchButton.getText().equals("Cancel")) {
            worker.cancel(false);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void queryTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            searchButton.doClick();
        }
    }//GEN-LAST:event_queryTextFieldKeyPressed

    public void doSearch() {

        // update the gui to signify it starting
        sourceLabel.setText("");
        sourceLabel.setToolTipText("");
        sizeLabel.setText("");
        statusLabel.setText("Searching...");
        loadingLabel.setIcon(new ImageIcon(this.getClass().getResource("/resources/loading-icon-2.gif")));
        searchButton.setText("Cancel");
        confirmButton.setEnabled(false);
        googleImagesButton.setEnabled(false);

        // do the search
        worker.execute();
    }

    private List<Icon> getIconsFromImages(List<ImageSearchResponse> responses) {
        List<Icon> scaledIcons = new ArrayList<>();
        for (ImageSearchResponse isr : responses) {
            byte[] bytes = Utils.getBytesFromBufferedImage(isr.getBImage());
            scaledIcons.add(Utils.getScaledImage(bytes, 250));
        }
        return scaledIcons;
    }

    private void confirmImage() {
        foundCover = responses.get(currentIconIndex).getBImage();
        // TODO get this from settings
        int dim = 640;
        File outputFile = Utils.createImageFile(foundCover, dir, dim);
        if (outputFile.exists()) {
            rows.forEach((row) -> {
                Main.frame.songController.addIndividualCover(row, outputFile);
            });
        }
        Main.frame.updateConsole("Auto-added cover art for " + rows.size() + " file(s)!");
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlbumArtFinderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlbumArtFinderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlbumArtFinderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlbumArtFinderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel albumArtImageLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton googleImagesButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JTextField queryTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel sourceLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
