/*
   Proj:   Moose
   File:   AuditFrame.java
   Desc:   Main UI class for the JFrame containing the Audit/Cleanup functionality.
           Works with the AuditController to clean and audit directories, this class just handles all the UI.

   Copyright Pat Ripley 2018
 */

// package
package moose.views;

// imports
import com.mpfthprblmtq.commons.logger.Logger;
import com.mpfthprblmtq.commons.utils.FileUtils;
import com.mpfthprblmtq.commons.utils.StringUtils;
import moose.Moose;
import moose.controllers.AuditController;
import moose.controllers.CleanupController;
import moose.controllers.SongController;
import moose.services.IconService;
import moose.utilities.*;

import java.awt.Font;
import java.io.File;
import java.util.List;
import java.util.Objects;
import javax.swing.*;

import static moose.utilities.Constants.*;

// class AuditFrame
public class AuditFrame extends javax.swing.JFrame {

    // controllers
    public AuditController auditController;
    public CleanupController cleanupController;

    // services
    public IconService iconService = new IconService();

    // logger object
    static Logger logger = Moose.getLogger();

    /**
     * Creates new form AuditFrame
     */
    public AuditFrame(Frame frame, SongController songController) {
        initComponents();

        // initialize the controllers
        auditController = new AuditController(frame, this, songController);
        cleanupController = new CleanupController(this);

        init();
    }

    private void init() {
        pathLabel.setText(populatePathLabel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        auditPanel = new javax.swing.JPanel();
        auditProgressBar = new javax.swing.JProgressBar();
        auditCurrentlyScanningLabel = new javax.swing.JLabel();
        previousFolderButton = new javax.swing.JButton();
        nextFolderButton = new javax.swing.JButton();
        attemptAutoFixButton = new javax.swing.JButton();
        ID3TagCheck = new javax.swing.JLabel();
        filenameCheck = new javax.swing.JLabel();
        coverArtCheck = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        auditAnalyzeButton = new javax.swing.JButton();
        auditStartButton = new javax.swing.JButton();
        auditViewResultsButton = new javax.swing.JButton();
        currentDirLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        auditResultsTextArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        advanceOnAutoFixCheckbox = new javax.swing.JCheckBox();
        cleanupPanel = new javax.swing.JPanel();
        cleanupCurrentlyScanningLabel = new javax.swing.JLabel();
        cleanupProgressBar = new javax.swing.JProgressBar();
        cleanupAnalyzeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cleanupResultsTextArea = new javax.swing.JTextArea();
        mp3asdCheckBox = new javax.swing.JCheckBox();
        wavCheckBox = new javax.swing.JCheckBox();
        flacCheckBox = new javax.swing.JCheckBox();
        zipCheckBox = new javax.swing.JCheckBox();
        windowsCheckBox = new javax.swing.JCheckBox();
        everythingElseCheckBox = new javax.swing.JCheckBox();
        imagesCheckBox = new javax.swing.JCheckBox();
        cleanupViewResultsButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();
        deleteSelectedButton = new javax.swing.JButton();
        chooseFolderButton = new javax.swing.JButton();
        pathLabel = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Audit Music");
        setResizable(false);

        tabbedPane.setForeground(new java.awt.Color(1, 1, 1));

        auditCurrentlyScanningLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        auditCurrentlyScanningLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        auditCurrentlyScanningLabel.setToolTipText("");
        auditCurrentlyScanningLabel.setMaximumSize(new java.awt.Dimension(400, 15));
        auditCurrentlyScanningLabel.setMinimumSize(new java.awt.Dimension(400, 15));
        auditCurrentlyScanningLabel.setPreferredSize(new java.awt.Dimension(400, 15));

        previousFolderButton.setText("<-- Previous");
        previousFolderButton.setEnabled(false);
        previousFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousFolderButtonActionPerformed(evt);
            }
        });

        nextFolderButton.setText("Save & Next -->");
        nextFolderButton.setEnabled(false);
        nextFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFolderButtonActionPerformed(evt);
            }
        });

        attemptAutoFixButton.setText("Attempt Auto Fix");
        attemptAutoFixButton.setEnabled(false);
        attemptAutoFixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attemptAutoFixButtonActionPerformed(evt);
            }
        });

        ID3TagCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        filenameCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coverArtCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        label3.setText("Every file has necessary ID3Tag information");
        label3.setEnabled(false);

        label4.setText("File names and directories all match standard");
        label4.setEnabled(false);

        label5.setText("Has cover art associated with the folder");
        label5.setEnabled(false);

        label2.setText("Current Folder:");
        label2.setEnabled(false);

        auditAnalyzeButton.setText("Perform Analysis");
        auditAnalyzeButton.setEnabled(false);
        auditAnalyzeButton.setMaximumSize(new java.awt.Dimension(150, 40));
        auditAnalyzeButton.setMinimumSize(new java.awt.Dimension(150, 40));
        auditAnalyzeButton.setPreferredSize(new java.awt.Dimension(150, 40));
        auditAnalyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditAnalyzeButtonActionPerformed(evt);
            }
        });

        auditStartButton.setText("Start Audit");
        auditStartButton.setEnabled(false);
        auditStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditStartButtonActionPerformed(evt);
            }
        });

        auditViewResultsButton.setText("View Results");
        auditViewResultsButton.setEnabled(false);
        auditViewResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditViewResultsButtonActionPerformed(evt);
            }
        });

        currentDirLabel.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        currentDirLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        currentDirLabel.setText(" ");
        currentDirLabel.setMaximumSize(new java.awt.Dimension(17, 339));
        currentDirLabel.setMinimumSize(new java.awt.Dimension(17, 339));
        currentDirLabel.setPreferredSize(new java.awt.Dimension(17, 339));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(175, 89));

        auditResultsTextArea.setEditable(false);
        auditResultsTextArea.setColumns(20);
        auditResultsTextArea.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        auditResultsTextArea.setRows(5);
        auditResultsTextArea.setMaximumSize(new java.awt.Dimension(175, 244));
        auditResultsTextArea.setMinimumSize(new java.awt.Dimension(175, 244));
        jScrollPane2.setViewportView(auditResultsTextArea);

        advanceOnAutoFixCheckbox.setText("Advance on successful Autofix");

        javax.swing.GroupLayout auditPanelLayout = new javax.swing.GroupLayout(auditPanel);
        auditPanel.setLayout(auditPanelLayout);
        auditPanelLayout.setHorizontalGroup(
            auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(auditPanelLayout.createSequentialGroup()
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(auditProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(auditCurrentlyScanningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(auditPanelLayout.createSequentialGroup()
                                .addComponent(coverArtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(auditPanelLayout.createSequentialGroup()
                                .addComponent(ID3TagCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(auditPanelLayout.createSequentialGroup()
                                .addComponent(filenameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(currentDirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(auditPanelLayout.createSequentialGroup()
                                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(auditAnalyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(auditStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(auditViewResultsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auditPanelLayout.createSequentialGroup()
                        .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(auditPanelLayout.createSequentialGroup()
                                .addComponent(previousFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(advanceOnAutoFixCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attemptAutoFixButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextFolderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        auditPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {nextFolderButton, previousFolderButton});

        auditPanelLayout.setVerticalGroup(
            auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(auditCurrentlyScanningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(auditProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(auditAnalyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(auditViewResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(auditStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auditPanelLayout.createSequentialGroup()
                        .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID3TagCheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filenameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coverArtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attemptAutoFixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advanceOnAutoFixCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(previousFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        auditPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {attemptAutoFixButton, nextFolderButton, previousFolderButton});

        tabbedPane.addTab("Audit", auditPanel);

        cleanupCurrentlyScanningLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        cleanupCurrentlyScanningLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cleanupCurrentlyScanningLabel.setToolTipText("");
        cleanupCurrentlyScanningLabel.setMaximumSize(new java.awt.Dimension(400, 15));
        cleanupCurrentlyScanningLabel.setMinimumSize(new java.awt.Dimension(400, 15));
        cleanupCurrentlyScanningLabel.setPreferredSize(new java.awt.Dimension(400, 15));

        cleanupAnalyzeButton.setText("Perform Analysis");
        cleanupAnalyzeButton.setEnabled(false);
        cleanupAnalyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanupAnalyzeButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");

        cleanupResultsTextArea.setEditable(false);
        cleanupResultsTextArea.setColumns(20);
        cleanupResultsTextArea.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        cleanupResultsTextArea.setRows(5);
        cleanupResultsTextArea.setWrapStyleWord(true);
        cleanupResultsTextArea.setEnabled(false);
        jScrollPane1.setViewportView(cleanupResultsTextArea);

        mp3asdCheckBox.setText(".mp3.asd");
        mp3asdCheckBox.setEnabled(false);
        mp3asdCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mp3asdCheckBoxStateChanged(evt);
            }
        });

        wavCheckBox.setText(".wav");
        wavCheckBox.setEnabled(false);
        wavCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                wavCheckBoxStateChanged(evt);
            }
        });

        flacCheckBox.setText(".flac");
        flacCheckBox.setEnabled(false);
        flacCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                flacCheckBoxStateChanged(evt);
            }
        });

        zipCheckBox.setText(".zip");
        zipCheckBox.setEnabled(false);
        zipCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zipCheckBoxStateChanged(evt);
            }
        });

        windowsCheckBox.setText("Windows files");
        windowsCheckBox.setEnabled(false);
        windowsCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                windowsCheckBoxStateChanged(evt);
            }
        });

        everythingElseCheckBox.setText("Other files");
        everythingElseCheckBox.setEnabled(false);
        everythingElseCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                everythingElseCheckBoxStateChanged(evt);
            }
        });

        imagesCheckBox.setText("Images (Excludes cover art images, i.e. cover.*)");
        imagesCheckBox.setEnabled(false);
        imagesCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                imagesCheckBoxStateChanged(evt);
            }
        });

        cleanupViewResultsButton.setText("View Results");
        cleanupViewResultsButton.setEnabled(false);
        cleanupViewResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanupViewResultsButtonActionPerformed(evt);
            }
        });

        deleteAllButton.setText("Delete All");
        deleteAllButton.setEnabled(false);
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });

        deleteSelectedButton.setText("Delete Selected");
        deleteSelectedButton.setEnabled(false);
        deleteSelectedButton.setMaximumSize(new java.awt.Dimension(97, 40));
        deleteSelectedButton.setMinimumSize(new java.awt.Dimension(97, 40));
        deleteSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cleanupPanelLayout = new javax.swing.GroupLayout(cleanupPanel);
        cleanupPanel.setLayout(cleanupPanelLayout);
        cleanupPanelLayout.setHorizontalGroup(
            cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cleanupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cleanupPanelLayout.createSequentialGroup()
                        .addComponent(flacCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zipCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(everythingElseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cleanupPanelLayout.createSequentialGroup()
                        .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cleanupPanelLayout.createSequentialGroup()
                                .addComponent(wavCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mp3asdCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(windowsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cleanupPanelLayout.createSequentialGroup()
                                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cleanupAnalyzeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cleanupViewResultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addComponent(cleanupProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cleanupCurrentlyScanningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cleanupPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteSelectedButton, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                        .addContainerGap())))
        );

        cleanupPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteAllButton, deleteSelectedButton});

        cleanupPanelLayout.setVerticalGroup(
            cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cleanupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cleanupCurrentlyScanningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cleanupProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cleanupPanelLayout.createSequentialGroup()
                        .addComponent(cleanupAnalyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanupViewResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wavCheckBox)
                    .addComponent(windowsCheckBox)
                    .addComponent(mp3asdCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flacCheckBox)
                    .addComponent(everythingElseCheckBox)
                    .addComponent(zipCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteSelectedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cleanupPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteAllButton, deleteSelectedButton});

        tabbedPane.addTab("Cleanup", cleanupPanel);

        chooseFolderButton.setText("Choose Folder...");
        chooseFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFolderButtonActionPerformed(evt);
            }
        });

        pathLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        pathLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        label1.setText("Audit/Cleanup Folder:");
        label1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseFolderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseFolderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFolderButtonActionPerformed
        auditController.nextFolder();
        this.toFront();
        this.requestFocus();
    }//GEN-LAST:event_nextFolderButtonActionPerformed

    /**
     * Handles the previous folder/album button press
     *
     * @param evt
     */
    private void previousFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousFolderButtonActionPerformed
        auditController.previousFolder();
        this.toFront();
        this.requestFocus();
    }//GEN-LAST:event_previousFolderButtonActionPerformed

    /**
     * Handles the choose folder button press
     *
     * @param evt
     */
    private void chooseFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFolderButtonActionPerformed
        chooseFolder();
        
        if(auditController.getFolder() != null) {
            auditAnalyzeButton.setEnabled(true);
            cleanupAnalyzeButton.setEnabled(true);
        }
    }//GEN-LAST:event_chooseFolderButtonActionPerformed

    /**
     * Handles the start audit button press
     *
     * @param evt
     */
    private void auditStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditStartButtonActionPerformed
        if (auditStartButton.getText().equals("Start Audit")) {
            startAudit();
        } else if (auditStartButton.getText().equals("Stop Audit")) {
            stopAudit();
        }
    }//GEN-LAST:event_auditStartButtonActionPerformed

    /**
     * Handles the stop audit button press
     *
     * @param evt
     */
    private void auditViewResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditViewResultsButtonActionPerformed
        viewResults(Constants.AUDIT);
    }//GEN-LAST:event_auditViewResultsButtonActionPerformed

    /**
     * Handles the analyze button press
     *
     * @param evt
     */
    private void cleanupAnalyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanupAnalyzeButtonActionPerformed
        cleanup();
    }//GEN-LAST:event_cleanupAnalyzeButtonActionPerformed

    /**
     * Handles the delete all button press
     *
     * @param evt
     */
    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
        int returnVal = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete all extra files?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (returnVal == 0) {
            cleanupController.deleteAll();
        }
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    /**
     * Handles the delete selected button press
     *
     * @param evt
     */
    private void deleteSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedButtonActionPerformed
        int returnVal = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete the selected extra files?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (returnVal == 0) {
            cleanupController.deleteSelected(
                    mp3asdCheckBox.isSelected(),
                    flacCheckBox.isSelected(),
                    wavCheckBox.isSelected(),
                    zipCheckBox.isSelected(),
                    imagesCheckBox.isSelected(),
                    windowsCheckBox.isSelected(),
                    everythingElseCheckBox.isSelected());
        }
    }//GEN-LAST:event_deleteSelectedButtonActionPerformed

    /**
     * Handles the view results button press
     *
     * @param evt
     */
    private void cleanupViewResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanupViewResultsButtonActionPerformed
        viewResults(Constants.CLEANUP);
    }//GEN-LAST:event_cleanupViewResultsButtonActionPerformed

    private void wavCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_wavCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_wavCheckBoxStateChanged

    private void flacCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_flacCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_flacCheckBoxStateChanged

    private void mp3asdCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mp3asdCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_mp3asdCheckBoxStateChanged

    private void zipCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zipCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_zipCheckBoxStateChanged

    private void windowsCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_windowsCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_windowsCheckBoxStateChanged

    private void everythingElseCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_everythingElseCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_everythingElseCheckBoxStateChanged

    private void imagesCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_imagesCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_imagesCheckBoxStateChanged

    private void auditAnalyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditAnalyzeButtonActionPerformed
        startAuditAnalysis();
    }//GEN-LAST:event_auditAnalyzeButtonActionPerformed

    private void attemptAutoFixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attemptAutoFixButtonActionPerformed
        autoFix();
    }//GEN-LAST:event_attemptAutoFixButtonActionPerformed

    public void startAuditAnalysis() {
        // make a swing worker do the image search in a separate thread so I can update the GUI
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                auditResultsTextArea.setText(auditController.analyze());
                auditViewResultsButton.setEnabled(true);    // enable the buttons used for audit now that we have results
                auditStartButton.setEnabled(true);
                return null;    // don't return anything since we're just playing with threads
            }
        };

        // e x e c u t e
        worker.execute();
    }

    /**
     * Function to get the folder to audit/cleanup
     * Sets the folder ivar in the auditController
     */
    public void chooseFolder() {

        // choose a folder
        File folder = Objects.requireNonNull(FileUtils.launchJFileChooser(
                "Select a folder to audit/cleanup",
                "Select",
                JFileChooser.DIRECTORIES_ONLY,
                false,
                null,
                null))[0];

        if(folder != null) {
            // set the file ivar in the controllers
            auditController.setFolder(folder);
            cleanupController.setFolder(folder);

            // update some graphics
            label1.setEnabled(true);
            pathLabel.setText(folder.getPath());
            resetAuditFrame();
        }
        // else nothing was chosen
    }

    public void updateConsole(String s) {
        auditResultsTextArea.setText(s);
    }

    public boolean shouldAdvanceOnAutofix() {
        return advanceOnAutoFixCheckbox.isSelected();
    }

    public void next() {
        nextFolderButton.doClick();
    }

    /**
     * Starts the audit
     */
    private void startAudit() {
        auditAnalyzeButton.setEnabled(false);
        chooseFolderButton.setEnabled(false);
        auditViewResultsButton.setEnabled(true);
        nextFolderButton.setEnabled(true);
        previousFolderButton.setEnabled(true);
        auditStartButton.setText("Stop Audit");
        label3.setEnabled(true);
        label4.setEnabled(true);
        label5.setEnabled(true);
        cleanupAnalyzeButton.setEnabled(false);
        cleanupViewResultsButton.setEnabled(false);
        deleteAllButton.setEnabled(false);
        deleteSelectedButton.setEnabled(false);
        auditController.startAudit();
    }

    /**
     * Stops the audit
     */
    private void stopAudit() {
        auditController.stopAudit();
        resetAuditFrame();
        auditStartButton.setEnabled(true);
        auditStartButton.setText("Start Audit");
    }

    /**
     * Clean up clean up everybody do your share
     */
    private void cleanup() {
        mp3asdCheckBox.setEnabled(true);
        flacCheckBox.setEnabled(true);
        wavCheckBox.setEnabled(true);
        zipCheckBox.setEnabled(true);
        windowsCheckBox.setEnabled(true);
        everythingElseCheckBox.setEnabled(true);
        imagesCheckBox.setEnabled(true);
        deleteAllButton.setEnabled(true);
        cleanupResultsTextArea.setEnabled(true);
        cleanupResultsTextArea.setText(cleanupController.analyze());

        // enable the button used for viewing now that we have results
        cleanupViewResultsButton.setEnabled(true);
    }

    /**
     * Attempts to auto fix things
     */
    private void autoFix() {
        auditController.autoFix();
    }

    /**
     * Populates the path label with the one in settings, or nothing if it's not there
     */
    public String populatePathLabel() {
        if (Moose.getSettings().getLibraryLocation().isEmpty()) {
            return StringUtils.EMPTY;
        } else {
            auditController.setFolder(new File(Moose.getSettings().getLibraryLocation()));
            cleanupController.setFolder(new File(Moose.getSettings().getLibraryLocation()));
            label1.setEnabled(true);

            auditAnalyzeButton.setEnabled(true);
            cleanupAnalyzeButton.setEnabled(true);
            
            return Moose.getSettings().getLibraryLocation();
        }
    }

    /**
     * Sets the next button text
     */
    public void setNextButtonText(String text) {
        nextFolderButton.setText(text);
    }

    /**
     * Shows the result of the audit/cleanup
     *
     * @param type the type of results needed
     */
    public void viewResults(int type) {
        if (type == Constants.AUDIT) {
            JOptionPane.showMessageDialog(null, buildResultsPanel(Constants.AUDIT), "Audit Analysis Results", JOptionPane.PLAIN_MESSAGE);
        } else if (type == Constants.CLEANUP) {
            JOptionPane.showMessageDialog(null, buildResultsPanel(Constants.CLEANUP), "Cleanup Analysis Results", JOptionPane.PLAIN_MESSAGE);
        }
    }

    /**
     * Assembles the JPanel for the dialog that shows the results of a cleanup
     * audit
     *
     * @param type the type of results needed
     * @return a fully assembled JPanel
     */
    public JPanel buildResultsPanel(int type) {

        // header JLabel
        JLabel cleanupPathLabel = new JLabel("Audit folder: " + auditController.getFolder().getPath());

        // text area
        JTextArea ta = new JTextArea(20, 100);
        ta.setEditable(false);
        ta.setFont(new Font("Monospaced", Font.PLAIN, 12));
        switch (type) {
            case Constants.AUDIT:
                ta.setText(auditController.getResults());
                break;
            case Constants.CLEANUP:
                ta.setText(cleanupController.getResults());
                break;
        }

        // add it all to a panel
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(cleanupPathLabel);
        panel.add(Box.createVerticalStrut(10));
        panel.add(new JScrollPane(ta));

        // return said panel
        return panel;
    }

    /**
     * Refreshes the three checks and the current directory when a new album is
     * loaded
     */
    public void refreshAuditFrame(List<Boolean> checkResults, String currentDirectory) {

        // set the controller ivars
        auditController.setIvars(checkResults.get(ID3), checkResults.get(FILENAMES), checkResults.get(COVER), currentDirectory);

        // set the pass/fail icons
        ID3TagCheck.setIcon(checkResults.get(ID3) ? iconService.get(IconService.AUDIT_FAIL) : iconService.get(IconService.AUDIT_PASS));
        filenameCheck.setIcon(checkResults.get(Constants.FILENAMES) ? iconService.get(IconService.AUDIT_FAIL) : iconService.get(IconService.AUDIT_PASS));
        coverArtCheck.setIcon(checkResults.get(Constants.COVER) ? iconService.get(IconService.AUDIT_FAIL) : iconService.get(IconService.AUDIT_PASS));

        // set the attempt fix button to enabled if there's anything to fix
        attemptAutoFixButton.setEnabled(checkResults.get(ID3) || checkResults.get(Constants.COVER) || checkResults.get(Constants.FILENAMES));

        // update the current directory label
        currentDirLabel.setText(auditController.getCurrentDirString(currentDirectory));
    }

    /**
     * Checks to see if the deleteSelectedButton should be set enabled
     *
     * @return the result of the check
     */
    public boolean getDeleteSelectedButtonStatus() {
        return (wavCheckBox.isSelected()
                || flacCheckBox.isSelected()
                || mp3asdCheckBox.isSelected()
                || zipCheckBox.isSelected()
                || windowsCheckBox.isSelected()
                || imagesCheckBox.isSelected()
                || everythingElseCheckBox.isSelected());
    }

    /**
     * Updates the currentlyScanningLabel
     */
    public void updateAuditCurrentlyScanningLabel(String s) {
        auditCurrentlyScanningLabel.setText(s);
    }

    /**
     * Updates the currentlyScanningLabel
     */
    public void updateCleanupCurrentlyScanningLabel(String s) {
        cleanupCurrentlyScanningLabel.setText(s);
    }

    /**
     * Updates the audit progressBar
     */
    public void updateAuditProgressBar(int percentage) {
        auditProgressBar.setValue(percentage);
    }

    /**
     * Updates the cleanup progressBar
     */
    public void updateCleanupProgressBar(int percentage) {
        cleanupProgressBar.setValue(percentage);
    }

    /**
     * Sets the horizontal alignment of the given label
     */
    public void setAuditCurrentlyScanningLabelHorizontalAlignment(int alignment) {
        auditCurrentlyScanningLabel.setHorizontalAlignment(alignment);
    }

    /**
     * Sets the horizontal alignment of the given label
     */
    public void setCleanupCurrentlyScanningLabelHorizontalAlignment(int alignment) {
        cleanupCurrentlyScanningLabel.setHorizontalAlignment(alignment);
    }

    /**
     * Sets the audit frame back to disabled
     */
    public void resetAuditFrame() {

        // random labels
        label1.setEnabled(false);
        label2.setEnabled(false);
        label3.setEnabled(false);
        label4.setEnabled(false);
        label5.setEnabled(false);

        // choose folder
        chooseFolderButton.setEnabled(true);

        // audit fields
        auditCurrentlyScanningLabel.setText(StringUtils.EMPTY);
        auditProgressBar.setValue(0);
        auditStartButton.setEnabled(false);
        auditStartButton.setText("Start Audit");
        auditViewResultsButton.setEnabled(false);
        auditResultsTextArea.setText(StringUtils.EMPTY);
        ID3TagCheck.setIcon(null);
        filenameCheck.setIcon(null);
        coverArtCheck.setIcon(null);
        currentDirLabel.setText(StringUtils.EMPTY);
        previousFolderButton.setEnabled(false);
        nextFolderButton.setEnabled(false);
        attemptAutoFixButton.setEnabled(false);
        nextFolderButton.setText("Save & Next -->");

        // cleanup fields
        cleanupAnalyzeButton.setEnabled(true);
        cleanupViewResultsButton.setEnabled(false);
        cleanupResultsTextArea.setText(StringUtils.EMPTY);
        wavCheckBox.setSelected(false);
        wavCheckBox.setEnabled(false);
        mp3asdCheckBox.setSelected(false);
        mp3asdCheckBox.setEnabled(false);
        windowsCheckBox.setSelected(false);
        windowsCheckBox.setEnabled(false);
        flacCheckBox.setSelected(false);
        flacCheckBox.setEnabled(false);
        zipCheckBox.setSelected(false);
        zipCheckBox.setEnabled(false);
        everythingElseCheckBox.setSelected(false);
        everythingElseCheckBox.setEnabled(false);
        imagesCheckBox.setSelected(false);
        imagesCheckBox.setEnabled(false);
        deleteAllButton.setEnabled(false);
        deleteSelectedButton.setEnabled(false);
        this.toFront();
        this.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID3TagCheck;
    private javax.swing.JCheckBox advanceOnAutoFixCheckbox;
    private javax.swing.JButton attemptAutoFixButton;
    private javax.swing.JButton auditAnalyzeButton;
    private javax.swing.JLabel auditCurrentlyScanningLabel;
    private javax.swing.JPanel auditPanel;
    private javax.swing.JProgressBar auditProgressBar;
    private javax.swing.JTextArea auditResultsTextArea;
    private javax.swing.JButton auditStartButton;
    private javax.swing.JButton auditViewResultsButton;
    private javax.swing.JButton chooseFolderButton;
    private javax.swing.JButton cleanupAnalyzeButton;
    private javax.swing.JLabel cleanupCurrentlyScanningLabel;
    private javax.swing.JPanel cleanupPanel;
    private javax.swing.JProgressBar cleanupProgressBar;
    private javax.swing.JTextArea cleanupResultsTextArea;
    private javax.swing.JButton cleanupViewResultsButton;
    private javax.swing.JLabel coverArtCheck;
    private javax.swing.JLabel currentDirLabel;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteSelectedButton;
    private javax.swing.JCheckBox everythingElseCheckBox;
    private javax.swing.JLabel filenameCheck;
    private javax.swing.JCheckBox flacCheckBox;
    private javax.swing.JCheckBox imagesCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JCheckBox mp3asdCheckBox;
    private javax.swing.JButton nextFolderButton;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JButton previousFolderButton;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JCheckBox wavCheckBox;
    private javax.swing.JCheckBox windowsCheckBox;
    private javax.swing.JCheckBox zipCheckBox;
    // End of variables declaration//GEN-END:variables
}
