/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moose;

import com.mpatric.mp3agic.InvalidDataException;
import com.mpatric.mp3agic.Mp3File;
import com.mpatric.mp3agic.UnsupportedTagException;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author pat
 */
public class AuditFrame extends javax.swing.JFrame {

    // some ivars
    int auditCount;
    ArrayList<File> albums = new ArrayList<>();
    File auditFolder;
    File currentDir;

    // some constants
    public final int AUDIT = 1;
    public final int CLEANUP = 2;

    // logger object
    Logger logger = new Logger();

    // Arraylist for files found
    ArrayList<ArrayList<String>> cleanupFilePathList = new ArrayList<>(Arrays.asList(
            new ArrayList<>(), // mp3.asd
            new ArrayList<>(), // flac
            new ArrayList<>(), // wav
            new ArrayList<>(), // zip
            new ArrayList<>(), // image files
            new ArrayList<>(), // windows files
            new ArrayList<>()));    // other files

    ArrayList<ArrayList<String>> auditFilePathList = new ArrayList<>(Arrays.asList(
            new ArrayList<>(), // id3
            new ArrayList<>(), // filenames
            new ArrayList<>()));    // cover art

    /**
     * Creates new form AuditFrame
     */
    public AuditFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        auditPanel = new javax.swing.JPanel();
        previousFolderButton = new javax.swing.JButton();
        nextFolderButton = new javax.swing.JButton();
        ID3TagCheck = new javax.swing.JLabel();
        filenameCheck = new javax.swing.JLabel();
        coverArtCheck = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        auditAnalyzeButton = new javax.swing.JButton();
        auditStartButton = new javax.swing.JButton();
        auditViewResultsButton = new javax.swing.JButton();
        currentDirLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        auditResultsTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        cleanupAnalyzeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cleanupResultsTextArea = new javax.swing.JTextArea();
        mp3asdCheckBox = new javax.swing.JCheckBox();
        wavCheckBox = new javax.swing.JCheckBox();
        flacCheckBox = new javax.swing.JCheckBox();
        zipCheckBox = new javax.swing.JCheckBox();
        windowsCheckBox = new javax.swing.JCheckBox();
        everythingElseCheckBox = new javax.swing.JCheckBox();
        imagesCheckBox = new javax.swing.JCheckBox();
        cleanupViewResultsButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();
        deleteSelectedButton = new javax.swing.JButton();
        chooseFolderButton = new javax.swing.JButton();
        pathLabel = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Audit Music");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        previousFolderButton.setText("<-- Previous");
        previousFolderButton.setEnabled(false);
        previousFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousFolderButtonActionPerformed(evt);
            }
        });

        nextFolderButton.setText("Save & Next -->");
        nextFolderButton.setEnabled(false);
        nextFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFolderButtonActionPerformed(evt);
            }
        });

        ID3TagCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        filenameCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coverArtCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        label3.setText("Every file has necessary ID3Tag information");
        label3.setEnabled(false);

        label4.setText("Filenames all match standard");
        label4.setEnabled(false);

        label5.setText("Has cover art associated with the folder");
        label5.setEnabled(false);

        label2.setText("Current Folder:");
        label2.setEnabled(false);

        auditAnalyzeButton.setText("Perform Analysis");
        auditAnalyzeButton.setEnabled(false);
        auditAnalyzeButton.setMaximumSize(new java.awt.Dimension(150, 40));
        auditAnalyzeButton.setMinimumSize(new java.awt.Dimension(150, 40));
        auditAnalyzeButton.setPreferredSize(new java.awt.Dimension(150, 40));
        auditAnalyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditAnalyzeButtonActionPerformed(evt);
            }
        });

        auditStartButton.setText("Start Audit");
        auditStartButton.setEnabled(false);
        auditStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditStartButtonActionPerformed(evt);
            }
        });

        auditViewResultsButton.setText("View Results");
        auditViewResultsButton.setEnabled(false);
        auditViewResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditViewResultsButtonActionPerformed(evt);
            }
        });

        currentDirLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        currentDirLabel.setText(" ");
        currentDirLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        currentDirLabel.setMaximumSize(new java.awt.Dimension(17, 339));
        currentDirLabel.setMinimumSize(new java.awt.Dimension(17, 339));
        currentDirLabel.setPreferredSize(new java.awt.Dimension(17, 339));

        auditResultsTextArea.setEditable(false);
        auditResultsTextArea.setColumns(20);
        auditResultsTextArea.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        auditResultsTextArea.setRows(5);
        jScrollPane2.setViewportView(auditResultsTextArea);

        javax.swing.GroupLayout auditPanelLayout = new javax.swing.GroupLayout(auditPanel);
        auditPanel.setLayout(auditPanelLayout);
        auditPanelLayout.setHorizontalGroup(
            auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(auditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(coverArtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(ID3TagCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(filenameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(previousFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextFolderButton))
                    .addComponent(currentDirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2)
                            .addComponent(auditAnalyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(auditStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(auditViewResultsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        auditPanelLayout.setVerticalGroup(
            auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(auditAnalyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(auditViewResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(auditStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auditPanelLayout.createSequentialGroup()
                        .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID3TagCheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filenameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coverArtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabbedPane.addTab("Audit", auditPanel);

        cleanupAnalyzeButton.setText("Perform Analysis");
        cleanupAnalyzeButton.setEnabled(false);
        cleanupAnalyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanupAnalyzeButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");

        cleanupResultsTextArea.setEditable(false);
        cleanupResultsTextArea.setColumns(20);
        cleanupResultsTextArea.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        cleanupResultsTextArea.setRows(5);
        cleanupResultsTextArea.setWrapStyleWord(true);
        cleanupResultsTextArea.setEnabled(false);
        jScrollPane1.setViewportView(cleanupResultsTextArea);

        mp3asdCheckBox.setText(".mp3.asd");
        mp3asdCheckBox.setEnabled(false);
        mp3asdCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mp3asdCheckBoxStateChanged(evt);
            }
        });

        wavCheckBox.setText(".wav");
        wavCheckBox.setEnabled(false);
        wavCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                wavCheckBoxStateChanged(evt);
            }
        });

        flacCheckBox.setText(".flac");
        flacCheckBox.setEnabled(false);
        flacCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                flacCheckBoxStateChanged(evt);
            }
        });

        zipCheckBox.setText(".zip");
        zipCheckBox.setEnabled(false);
        zipCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zipCheckBoxStateChanged(evt);
            }
        });

        windowsCheckBox.setText("Windows files");
        windowsCheckBox.setEnabled(false);
        windowsCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                windowsCheckBoxStateChanged(evt);
            }
        });

        everythingElseCheckBox.setText("Other files");
        everythingElseCheckBox.setEnabled(false);
        everythingElseCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                everythingElseCheckBoxStateChanged(evt);
            }
        });

        imagesCheckBox.setText("Images (Excludes cover art images, i.e. cover.*)");
        imagesCheckBox.setEnabled(false);
        imagesCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                imagesCheckBoxStateChanged(evt);
            }
        });

        cleanupViewResultsButton.setText("View Results");
        cleanupViewResultsButton.setEnabled(false);
        cleanupViewResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanupViewResultsButtonActionPerformed(evt);
            }
        });

        deleteAllButton.setText("Delete All");
        deleteAllButton.setEnabled(false);
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });

        deleteSelectedButton.setText("Delete Selected");
        deleteSelectedButton.setEnabled(false);
        deleteSelectedButton.setMaximumSize(new java.awt.Dimension(97, 40));
        deleteSelectedButton.setMinimumSize(new java.awt.Dimension(97, 40));
        deleteSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(flacCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zipCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(everythingElseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(wavCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mp3asdCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(windowsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cleanupAnalyzeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cleanupViewResultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteSelectedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cleanupAnalyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanupViewResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wavCheckBox)
                    .addComponent(windowsCheckBox)
                    .addComponent(mp3asdCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flacCheckBox)
                    .addComponent(everythingElseCheckBox)
                    .addComponent(zipCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(deleteSelectedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPane.addTab("Cleanup", jPanel2);

        chooseFolderButton.setText("Choose Folder...");
        chooseFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFolderButtonActionPerformed(evt);
            }
        });

        pathLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        pathLabel.setText(" ");
        pathLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        label1.setText("Audit/Cleanup Folder:");
        label1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseFolderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseFolderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the next folder/album button press
     *
     * @param evt
     */
    private void nextFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFolderButtonActionPerformed
        nextAuditFolder();
    }//GEN-LAST:event_nextFolderButtonActionPerformed

    /**
     * Handles the previous folder/album button press
     *
     * @param evt
     */
    private void previousFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousFolderButtonActionPerformed
        previousAuditFolder();
    }//GEN-LAST:event_previousFolderButtonActionPerformed

    /**
     * Handles the choose folder button press
     *
     * @param evt
     */
    private void chooseFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFolderButtonActionPerformed
        chooseFolder();
        auditAnalyzeButton.setEnabled(true);
        auditStartButton.setEnabled(true);
        cleanupAnalyzeButton.setEnabled(true);
        importAlbums();
    }//GEN-LAST:event_chooseFolderButtonActionPerformed

    /**
     * Handles the start audit button press
     *
     * @param evt
     */
    private void auditStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditStartButtonActionPerformed
        if (auditStartButton.getText().equals("Start Audit")) {
            auditStartButton.setEnabled(false);
            auditViewResultsButton.setEnabled(true);
            nextFolderButton.setEnabled(true);
            previousFolderButton.setEnabled(true);
            auditStartButton.setText("Stop Audit");
            startAudit();
        } else if (auditStartButton.getText().equals("Stop Audit")) {
            stopAudit();
            resetAuditFrame();
            auditStartButton.setText("Start Audit");
        }
    }//GEN-LAST:event_auditStartButtonActionPerformed

    /**
     * Handles the stop audit button press
     *
     * @param evt
     */
    private void auditViewResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditViewResultsButtonActionPerformed
        viewResults(AUDIT);
    }//GEN-LAST:event_auditViewResultsButtonActionPerformed

    /**
     * Handles the analyze button press
     *
     * @param evt
     */
    private void cleanupAnalyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanupAnalyzeButtonActionPerformed
        mp3asdCheckBox.setEnabled(true);
        flacCheckBox.setEnabled(true);
        wavCheckBox.setEnabled(true);
        zipCheckBox.setEnabled(true);
        windowsCheckBox.setEnabled(true);
        everythingElseCheckBox.setEnabled(true);
        imagesCheckBox.setEnabled(true);
        deleteAllButton.setEnabled(true);
        cleanupResultsTextArea.setEnabled(true);

        analyze(CLEANUP);
    }//GEN-LAST:event_cleanupAnalyzeButtonActionPerformed

    /**
     * Handles the delete all button press
     *
     * @param evt
     */
    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
        int returnVal = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete all extra files?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (returnVal == 0) {
            deleteAll();
        }
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    /**
     * Handles the delete selected button press
     *
     * @param evt
     */
    private void deleteSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedButtonActionPerformed
        int returnVal = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete the selected extra files?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (returnVal == 0) {
            deleteSelected();
        }
    }//GEN-LAST:event_deleteSelectedButtonActionPerformed

    /**
     * Handles the view results button press
     *
     * @param evt
     */
    private void cleanupViewResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanupViewResultsButtonActionPerformed
        viewResults(CLEANUP);
    }//GEN-LAST:event_cleanupViewResultsButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        resetAuditFrame();
    }//GEN-LAST:event_formWindowClosed

    private void wavCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_wavCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_wavCheckBoxStateChanged

    private void flacCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_flacCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_flacCheckBoxStateChanged

    private void mp3asdCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mp3asdCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_mp3asdCheckBoxStateChanged

    private void zipCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zipCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_zipCheckBoxStateChanged

    private void windowsCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_windowsCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_windowsCheckBoxStateChanged

    private void everythingElseCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_everythingElseCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_everythingElseCheckBoxStateChanged

    private void imagesCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_imagesCheckBoxStateChanged
        deleteSelectedButton.setEnabled(getDeleteSelectedButtonStatus());
    }//GEN-LAST:event_imagesCheckBoxStateChanged

    private void auditAnalyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditAnalyzeButtonActionPerformed
        auditViewResultsButton.setEnabled(true);
        analyze(AUDIT);
    }//GEN-LAST:event_auditAnalyzeButtonActionPerformed

    /**
     * Shows the result of the audit/cleanup
     *
     * @param type the type of results needed
     */
    public void viewResults(int type) {
        if (type == AUDIT) {
            JOptionPane.showMessageDialog(null, buildResultsPanel(AUDIT), "Audit Analysis Results", JOptionPane.PLAIN_MESSAGE);
        } else if (type == CLEANUP) {
            JOptionPane.showMessageDialog(null, buildResultsPanel(CLEANUP), "Cleanup Analysis Results", JOptionPane.PLAIN_MESSAGE);
        }
    }

    /**
     * Assembles the JPanel for the dialog that shows the results of a cleanup
     * audit
     *
     * @param type the type of results needed
     * @return a fully assembled JPanel
     */
    public JPanel buildResultsPanel(int type) {

        // header JLabel
        JLabel cleanupPathLabel = new JLabel("Audit folder: " + auditFolder.getPath());

        // text area
        JTextArea ta = new JTextArea(20, 100);
        ta.setEditable(false);
        ta.setFont(new Font("Monospaced", Font.PLAIN, 12));
        switch (type) {
            case AUDIT:
                ta.setText(exportResultsToString(AUDIT));
                break;
            case CLEANUP:
                ta.setText(exportResultsToString(CLEANUP));
                break;
        }

        // add it all to a panel
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(cleanupPathLabel);
        panel.add(Box.createVerticalStrut(10));
        panel.add(new JScrollPane(ta));

        // return said panel
        return panel;
    }

    /**
     * Refreshes the three checks and the current directory when a new album is
     * loaded
     */
    public void refreshAuditFrame() {
        if (checkID3Tags(currentDir)) {
            ID3TagCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/check2.png")));
        } else {
            ID3TagCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/error.png")));
        }
        if (checkFilenames(currentDir)) {
            filenameCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/check2.png")));
        } else {
            filenameCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/error.png")));
        }
        if (checkFolderCover(currentDir)) {
            coverArtCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/check2.png")));
        } else {
            coverArtCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/error.png")));
        }
        currentDirLabel.setText(currentDir.getPath());
    }

    /**
     * Function to get the folder to audit and sets the auditFolder ivar
     */
    public void chooseFolder() {

        // use a filechooser to open the folder full of stuff
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setAcceptAllFileFilterUsed(false);

        // result of filechoosing
        int returnVal = fc.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            auditFolder = fc.getSelectedFile();
            label1.setEnabled(true);
            pathLabel.setText(auditFolder.getPath());
        }
    }

    /**
     * Creates a master list of files from the audit folder, then imports all
     * the albums into the albums ivar list
     */
    public void importAlbums() {

        // arraylist to store all the files
        ArrayList<File> allFiles = new ArrayList<>();
        allFiles = Main.frame.listFiles(auditFolder, allFiles);

        // traverse the list of files and add the albums to the albums ivar list
        for (File file : allFiles) {
            if (file.getName().endsWith(".mp3")) {
                File a = file.getParentFile();

                // folder is a multi-disk album
                if (a.getName().equals("CD1") || a.getName().equals("CD2")) {
                    a = a.getParentFile();
                }
                if (!albums.contains(a)) {
                    albums.add(a);
                }
            }
        }

        // sort them alphabetically
        Collections.sort(albums, (File o1, File o2) -> {
            String filename1 = o1.getPath().replace(auditFolder.getPath(), "");
            String filename2 = o2.getPath().replace(auditFolder.getPath(), "");
            return filename1.compareToIgnoreCase(filename2);
        });
    }

    /**
     * Checks to see if the deleteSelectedButton should be set enabled
     *
     * @return the result of the check
     */
    public boolean getDeleteSelectedButtonStatus() {
        return (wavCheckBox.isSelected()
                || flacCheckBox.isSelected()
                || mp3asdCheckBox.isSelected()
                || zipCheckBox.isSelected()
                || windowsCheckBox.isSelected()
                || imagesCheckBox.isSelected()
                || everythingElseCheckBox.isSelected());
    }

    /**
     * Called from the start audit button press Checks if an audit is already in
     * process first, then user decides to either start a new audit or continue
     * that existing audit
     */
    public void startAudit() {

        // check for an audit in process
        if (checkForExisitingAudit()) {
            Object[] options = new Object[]{"Cancel", "Start New", "Continue"};
            int returnVal = JOptionPane.showOptionDialog(
                    this,
                    "An exisiting audit is in process, do you want to continue?",
                    "Existing audit found",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    options,
                    null);
            switch (returnVal) {
                case 2:     // continue
                    continueAudit();
                    break;
                case 1:     // start a new one
                    newAudit();
                    break;
                default:
                    // do nothing
                    break;
            }
        } else {
            // existing audit not found, start a fresh one
            newAudit();
        }
    }

    /**
     * Start a brand new audit
     */
    public void newAudit() {

        // update graphics
        label3.setEnabled(true);
        label4.setEnabled(true);
        label5.setEnabled(true);

        // clear any residual files
        clearDoneFiles();

        // set some ivars
        auditCount = 0;
        currentDir = albums.get(auditCount);

        // sets up the audit frame with the three checks
        refreshAuditFrame();

        // open up a new Frame with the album preloaded
        Main.frame.dispose();
        Main.frame = new Frame(albums.get(auditCount));
        Main.launchFrame();
    }

    /**
     * Continue an existing audit
     */
    public void continueAudit() {

        // update graphics
        label3.setEnabled(true);
        label4.setEnabled(true);
        label5.setEnabled(true);

        // set some ivars
        auditCount = getNextAlbum();
        currentDir = albums.get(auditCount);

        // refreshes the audit frame with the three checks
        refreshAuditFrame();

        // open up a new Frame with the next album preloaded
        Main.frame.dispose();
        Main.frame = new Frame(currentDir);
        Main.launchFrame();
    }

    /**
     * Goes to the next audit album/folder
     */
    public void nextAuditFolder() {

        // sets the current album as done
        if (!checkIfDone(albums.get(auditCount))) {
            setDone(albums.get(auditCount));
        }

        // update the ivar
        auditCount++;

        // save the tracks here instead of forcing the user to save it in the main frame form
        Main.frame.saveAll();

        // check if the audit is done
        if (auditCount < albums.size()) {

            // refresh the frame with the new album and the checks
            currentDir = albums.get(auditCount);
            refreshAuditFrame();

            // close the current frame and open a new one with the new album preloaded
            Main.frame.dispose();
            Main.frame = new Frame(currentDir);
            Main.launchFrame();
            this.requestFocus();
        } else {
            // audit is done
            finishAudit();
        }
    }

    /**
     * Goes to the previous album/folder
     */
    public void previousAuditFolder() {

        // sets the current album as done
        if (!checkIfDone(albums.get(auditCount))) {
            setDone(albums.get(auditCount));
        }

        // prevent a negative auditCount
        if (auditCount <= 0) {
            // do nothing
        } else {

            // update ivars
            auditCount--;
            currentDir = albums.get(auditCount);

            // refresh the frame with the new album and the checks
            refreshAuditFrame();
            Main.frame.dispose();
            Main.frame = new Frame(currentDir);
            Main.launchFrame();
            this.requestFocus();
        }
    }

    /**
     * Stops the audit
     */
    public void stopAudit() {
        albums.clear();
        auditStartButton.setEnabled(true);
        Main.frame.dispose();
        Main.frame = new Frame();
        Main.launchFrame();
    }

    /**
     * Finishes the audit
     */
    public void finishAudit() {

        // set some ivars
        albums.clear();
        auditCount = 0;

        // launch a blank mainframe
        Main.frame.dispose();
        Main.frame = new Frame();
        Main.launchFrame();

        // reset the audit frame
        resetAuditFrame();

        // show that audit is done
        JOptionPane.showMessageDialog(null, "Audit is complete!", "Audit Completed", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Sets the audit frame back to disabled
     */
    public void resetAuditFrame() {
        tabbedPane.setSelectedIndex(0);
        label1.setEnabled(false);
        label2.setEnabled(false);
        label3.setEnabled(false);
        label4.setEnabled(false);
        label5.setEnabled(false);
        ID3TagCheck.setIcon(null);
        filenameCheck.setIcon(null);
        coverArtCheck.setIcon(null);
        previousFolderButton.setEnabled(false);
        nextFolderButton.setEnabled(false);
        currentDirLabel.setText("");
        pathLabel.setText("");
        auditAnalyzeButton.setEnabled(false);
        auditResultsTextArea.setText("");
        auditResultsTextArea.setEnabled(false);
        cleanupResultsTextArea.setText("");
        cleanupResultsTextArea.setEnabled(false);
        auditStartButton.setEnabled(false);
        auditViewResultsButton.setEnabled(false);
        cleanupAnalyzeButton.setEnabled(false);
        cleanupViewResultsButton.setEnabled(false);
        deleteAllButton.setEnabled(false);
        deleteSelectedButton.setEnabled(false);
        mp3asdCheckBox.setSelected(false);
        mp3asdCheckBox.setEnabled(false);
        wavCheckBox.setSelected(false);
        wavCheckBox.setEnabled(false);
        flacCheckBox.setSelected(false);
        flacCheckBox.setEnabled(false);
        zipCheckBox.setSelected(false);
        zipCheckBox.setEnabled(false);
        windowsCheckBox.setSelected(false);
        windowsCheckBox.setEnabled(false);
        everythingElseCheckBox.setSelected(false);
        everythingElseCheckBox.setEnabled(false);
        imagesCheckBox.setSelected(false);
        imagesCheckBox.setEnabled(false);
        this.requestFocus();
    }

    /**
     * Deletes all files in the cleanupFilePathList arraylist
     */
    public void deleteAll() {
        if (!iscleanupFilePathListEmpty()) {
            cleanupFilePathList.forEach((list) -> {
                deleteAllFilesInList(list);
            });
            // clear all the lists to reset counts
            clearLists(CLEANUP);
            // reset the statistics
            analyze(CLEANUP);
        } else {
            // show that there's nothing to delete
            JOptionPane.showMessageDialog(null, "Nothing to Delete!", "Delete All", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * Deletes only the checked file types
     */
    public void deleteSelected() {

        boolean nothingToDelete = true;

        if (mp3asdCheckBox.isSelected()) {
            nothingToDelete = cleanupFilePathList.get(0).isEmpty();
            deleteAllFilesInList(cleanupFilePathList.get(0));
            cleanupFilePathList.get(0).clear();
        }
        if (flacCheckBox.isSelected()) {
            nothingToDelete = nothingToDelete && cleanupFilePathList.get(1).isEmpty();
            deleteAllFilesInList(cleanupFilePathList.get(1));
            cleanupFilePathList.get(1).clear();
        }
        if (wavCheckBox.isSelected()) {
            nothingToDelete = nothingToDelete && cleanupFilePathList.get(2).isEmpty();
            deleteAllFilesInList(cleanupFilePathList.get(2));
            cleanupFilePathList.get(2).clear();
        }
        if (zipCheckBox.isSelected()) {
            nothingToDelete = nothingToDelete && cleanupFilePathList.get(3).isEmpty();
            deleteAllFilesInList(cleanupFilePathList.get(3));
            cleanupFilePathList.get(3).clear();
        }
        if (imagesCheckBox.isSelected()) {
            nothingToDelete = nothingToDelete && cleanupFilePathList.get(4).isEmpty();
            deleteAllFilesInList(cleanupFilePathList.get(4));
            cleanupFilePathList.get(4).clear();
        }
        if (windowsCheckBox.isSelected()) {
            nothingToDelete = nothingToDelete && cleanupFilePathList.get(5).isEmpty();
            deleteAllFilesInList(cleanupFilePathList.get(5));
            cleanupFilePathList.get(5).clear();
        }
        if (everythingElseCheckBox.isSelected()) {
            nothingToDelete = nothingToDelete && cleanupFilePathList.get(6).isEmpty();
            deleteAllFilesInList(cleanupFilePathList.get(6));
            cleanupFilePathList.get(6).clear();
        }

        if (nothingToDelete) {
            // show that there's nothing to delete
            JOptionPane.showMessageDialog(null, "Nothing to Delete!", "Delete Selected", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // clear all the lists to reset counts
            clearLists(CLEANUP);
            // reset the statistics
            analyze(CLEANUP);
        }
    }

    /**
     * Helper function used to delete files in a specific list
     *
     * @param list
     */
    public void deleteAllFilesInList(ArrayList<String> list) {
        list.stream().map((path) -> new File(path)).forEachOrdered((file) -> {
            if (file.exists()) {
                file.delete();
            } else {
                logger.logError("Tried to delete file in cleanup, but couldn't!");
            }
        });
    }

    /**
     * Helper function to clear all sublists in cleanupFilePathList
     *
     * @param type the type of lists to clear
     */
    public void clearLists(int type) {
        switch (type) {
            case CLEANUP:
                cleanupFilePathList.get(0).clear();
                cleanupFilePathList.get(1).clear();
                cleanupFilePathList.get(2).clear();
                cleanupFilePathList.get(3).clear();
                cleanupFilePathList.get(4).clear();
                cleanupFilePathList.get(5).clear();
                cleanupFilePathList.get(6).clear();
                break;
            case AUDIT:
                auditFilePathList.get(0).clear();
                auditFilePathList.get(1).clear();
                auditFilePathList.get(2).clear();
                break;
        }

    }

    /**
     * Helper function to check if any of the lists are empty
     *
     * @return the result of the check
     */
    public boolean iscleanupFilePathListEmpty() {
        return (cleanupFilePathList.get(0).isEmpty()
                && cleanupFilePathList.get(1).isEmpty()
                && cleanupFilePathList.get(2).isEmpty()
                && cleanupFilePathList.get(3).isEmpty()
                && cleanupFilePathList.get(4).isEmpty()
                && cleanupFilePathList.get(5).isEmpty()
                && cleanupFilePathList.get(6).isEmpty());
    }

    /**
     * Checks to see if in the audit folder there exists a done file in any of
     * its subfolders
     *
     * @return the result of the check, true for existing audit, false for no
     * existing audit
     */
    public boolean checkForExisitingAudit() {
        return albums.stream().anyMatch((album) -> (containsFile(album)));
    }

    /**
     * Helper function used to see if there's a done file in the specified
     * folder
     *
     * @param dir, the directory to check
     * @return the result of the search, true for file found, false for file not
     * found
     */
    public boolean containsFile(File dir) {
        File[] filesInAlbum = dir.listFiles();
        for (File file : filesInAlbum) {
            if (file.getName().equals("done")) {
                return true;
            }
        }
        return false;
    }

    /**
     * Function used to create a done file in the specified folder
     *
     * @param dir, the directory to create the file in
     */
    public void setDone(File dir) {
        String path = dir.getPath() + "/done";
        File done = new File(path);
        try {
            done.createNewFile();
        } catch (IOException ex) {
            Main.logger.logError("Error creating done file for auditing in folder: " + path, ex);
        }
    }

    /**
     * Checks if that specified directory/album is done
     *
     * @param dir, the directory to check
     * @return the result of the check, true for done, false for not done
     */
    public boolean checkIfDone(File dir) {
        File[] files = dir.listFiles();
        for (File file : files) {
            if (file.getName().equals("done")) {
                return true;
            }
        }
        return false;
    }

    /**
     * Gets the next album index in the albums arraylist
     *
     * @return the int index of that album
     */
    public int getNextAlbum() {
        for (File album : albums) {
            if (!checkIfDone(album)) {
                return albums.indexOf(album);
            }
        }
        return -1;
    }

    /**
     * Function used to clear all of the done files from the albums list
     */
    public void clearDoneFiles() {
        albums.stream().filter((album) -> (containsFile(album))).map((album) -> album.listFiles()).forEachOrdered((files) -> {
            for (File file : files) {
                if (file.getName().equals("done")) {
                    file.delete();
                }
            }
        });
    }

    /**
     * Checks the album/folder for a cover.* file (image file)
     *
     * @return the result of the check, true for a cover file exists, false for
     * a cover file doesn't exist
     */
    private boolean checkFolderCover(File dir) {

        // check the current directory ivar
        File[] files = dir.listFiles();
        for (File file : files) {
            if (file.getName().startsWith("cover")) {
                return true;
            }
        }
        return false;
    }

    /**
     * Checks all the files in a folder for the standardized file name
     *
     * @return the result of the check, true if all files are good, false if one
     * or more doesn't match
     */
    private boolean checkFilenames(File dir) {

        // create a list of all files from that directory
        ArrayList<File> files = new ArrayList<>();
        files = Main.frame.listFiles(dir, files);

        // regex to check
        String regex = "\\d\\d ((.)*)";

        // check all files in that list
        // also checks if the album artist is a label, since those files aren't formatted the same
        for (File file : files) {
            if (file.getName().endsWith(".mp3")) {
                if (!file.getName().matches(regex) && !isLabel(file)) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Checks all the mp3s in a folder for all the necessary id3 tags
     *
     * @return the result of the check, true if all mp3s are good, false if one
     * or more doesn't have all information needed
     */
    private boolean checkID3Tags(File dir) {

        // create a list of all files from that directory
        ArrayList<File> files = new ArrayList<>();
        files = Main.frame.listFiles(dir, files);

        // traverse the file list
        for (File file : files) {

            // check if it's an mp3
            if (file.getName().endsWith(".mp3")) {

                // mp3agic Mp3File object, used for the id3tags
                Mp3File mp3file;
                try {
                    // create the mp3file from the file's path
                    mp3file = new Mp3File(file.getAbsolutePath());

                    // if the mp3file doesn't have an id3tag
                    if (!mp3file.hasId3v2Tag()) {
                        return false;
                    }
                } catch (IOException | UnsupportedTagException | InvalidDataException ex) {
                    logger.logError("Exception when checking if an mp3 has id3 information!", ex);
                    mp3file = null;
                }

                // get the id3v2 info
                String title = mp3file.getId3v2Tag().getTitle();
                String artist = mp3file.getId3v2Tag().getArtist();
                String album = mp3file.getId3v2Tag().getAlbum();
                String albumartist = mp3file.getId3v2Tag().getAlbumArtist();
                String genre = mp3file.getId3v2Tag().getGenreDescription();
                String year = mp3file.getId3v2Tag().getYear();
                String track = mp3file.getId3v2Tag().getTrack();
                String disk = mp3file.getId3v2Tag().getPartOfSet();
                byte[] artwork_bytes = mp3file.getId3v2Tag().getAlbumImage();

                // check if it's a label, since those mp3s don't need as much information
                if (isLabel(dir)) {
                    if (title == null
                            || artist == null
                            || album == null
                            || albumartist == null
                            || genre == null
                            || artwork_bytes == null) {
                        return false;
                    }
                } else {
                    if (title == null
                            || artist == null
                            || album == null
                            || albumartist == null
                            || genre == null
                            || year == null
                            || track == null
                            || disk == null
                            || artwork_bytes == null) {
                        return false;
                    }
                }
            }
        }
        return true;
    }

    /**
     * Check if a directory is from a label
     *
     * @param dir, the directory to check
     * @return the result of the check, true if it is a label, false if it isn't
     * a label
     */
    public boolean isLabel(File dir) {
        String path = dir.getPath();
        return path.contains("/Genres/");
    }

    /**
     * Larger function used to check all the files in the auditFolder for any
     * files that don't really belong
     *
     * @param type the type of analysis to run
     */
    public void analyze(int type) {

        switch (type) {
            case CLEANUP:

                // reset everything
                clearLists(CLEANUP);

                // let's count the mp3s and covers, cause why not
                int mp3Count = 0;
                int coverCount = 0;

                // create a list of all files from that directory
                ArrayList<File> cleanupFiles = new ArrayList<>();
                cleanupFiles = Main.frame.listFiles(auditFolder, cleanupFiles);

                // traverse that list
                for (File file : cleanupFiles) {

                    // get the filename to check
                    String filename = file.getName();

                    // check the ending/extension
                    // add it to the specified sublist
                    if (filename.endsWith(".mp3")) {
                        mp3Count++;
                    } else if (filename.startsWith("cover.")) {
                        coverCount++;
                    } else if (filename.endsWith(".mp3.asd")) {
                        cleanupFilePathList.get(0).add(file.getPath());
                    } else if (filename.endsWith(".flac")) {
                        cleanupFilePathList.get(1).add(file.getPath());
                    } else if (filename.endsWith(".wav")) {
                        cleanupFilePathList.get(2).add(file.getPath());
                    } else if (filename.endsWith(".zip")) {
                        cleanupFilePathList.get(3).add(file.getPath());
                    } else if ((filename.endsWith(".png") || filename.endsWith(".jpg") || filename.endsWith(".jpeg") || filename.endsWith(".JPG"))
                            && !filename.startsWith("cover.")
                            && !file.getParentFile().getName().equals("artwork")) {
                        cleanupFilePathList.get(4).add(file.getPath());
                    } else if (filename.equals("Thumbs.db") || filename.startsWith("folder.")) {
                        cleanupFilePathList.get(5).add(file.getPath());
                    } else {
                        if (!(filename.endsWith(".png") || filename.endsWith(".jpg") || filename.endsWith(".jpeg") || filename.endsWith(".JPG"))
                                && !filename.equals("done")
                                && !filename.equals(".DS_Store")) {
                            cleanupFilePathList.get(6).add(file.getPath());
                        }
                    }
                }

                // update the results
                cleanupResultsTextArea.setText(
                        "MP3 Files:     " + mp3Count + "\n"
                        + "Cover Files:   " + coverCount + "\n"
                        + "ZIP Files:     " + cleanupFilePathList.get(3).size() + "\n"
                        + "ASD Files:     " + cleanupFilePathList.get(0).size() + "\n"
                        + "WAV Files:     " + cleanupFilePathList.get(2).size() + "\n"
                        + "FLAC Files:    " + cleanupFilePathList.get(1).size() + "\n"
                        + "Image Files:   " + cleanupFilePathList.get(4).size() + "\n"
                        + "Windows Files: " + cleanupFilePathList.get(5).size() + "\n"
                        + "Other Files:   " + cleanupFilePathList.get(6).size()
                );

                // enable the button used for viewing now that we have results
                cleanupViewResultsButton.setEnabled(true);

                break;

            case AUDIT:

                // reset everything
                clearLists(AUDIT);
                
//                // create a list of all files from that directory
//                ArrayList<File> auditFiles = new ArrayList<>();
//                auditFiles = Main.frame.listFiles(auditFolder, auditFiles);

                // traverse that list
                for (File dir : albums) {
                    if(!checkID3Tags(dir)) {
                        auditFilePathList.get(0).add(dir.getPath());
                    }
                    if(!checkFilenames(dir)) {
                        auditFilePathList.get(1).add(dir.getPath());
                    }
                    if(!checkFolderCover(dir)) {
                        auditFilePathList.get(2).add(dir.getPath());
                    }
                }
                
                // update the results
                auditResultsTextArea.setText(
                        "ID3Tags missing:   " + auditFilePathList.get(0).size() + "\n"
                      + "Filename issues:   " + auditFilePathList.get(1).size() + "\n"
                      + "Cover art missing: " + auditFilePathList.get(2).size()
                );
                
                // enable the button used for viewing now that we have results
                auditViewResultsButton.setEnabled(true);
                
                break;
        }
    }

    /**
     * Function used to export the results to a heavily formatted string
     *
     * @param type the type of results needed
     * @return a string representation of the results
     */
    public String exportResultsToString(int type) {

        // lets make a string
        String str = "\n";

        // do something based on the type
        switch (type) {
            case AUDIT:

                // id3tags
                str = str.concat(" Some ID3Tags missing:\n");
                for (String path : auditFilePathList.get(0)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");
                
                // id3tags
                str = str.concat(" Some filenames don't match standard:\n");
                for (String path : auditFilePathList.get(1)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");
                
                // cover art
                str = str.concat(" Cover art not found in folder:\n");
                for (String path : auditFilePathList.get(2)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");
                break;
            case CLEANUP:

                // zip files
                str = str.concat(" ZIP FILES:\n");
                for (String path : cleanupFilePathList.get(3)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");

                // mp3.asd files
                str = str.concat(" MP3.ASD FILES:\n");
                for (String path : cleanupFilePathList.get(0)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");

                // wav files
                str = str.concat(" WAV FILES:\n");
                for (String path : cleanupFilePathList.get(2)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");

                // flac files
                str = str.concat(" FLAC FILES:\n");
                for (String path : cleanupFilePathList.get(1)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");

                // image files
                str = str.concat(" IMAGE FILES:\n");
                for (String path : cleanupFilePathList.get(4)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");

                // windows files
                str = str.concat(" WINDOWS FILES:\n");
                for (String path : cleanupFilePathList.get(5)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");

                // other files
                str = str.concat(" OTHER FILES:\n");
                for (String path : cleanupFilePathList.get(6)) {
                    str = str.concat(" \t" + path + " \n");
                }
                str = str.concat("\n");

                break;
        }

        return str;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new AuditFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID3TagCheck;
    private javax.swing.JButton auditAnalyzeButton;
    private javax.swing.JPanel auditPanel;
    private javax.swing.JTextArea auditResultsTextArea;
    private javax.swing.JButton auditStartButton;
    private javax.swing.JButton auditViewResultsButton;
    private javax.swing.JButton chooseFolderButton;
    private javax.swing.JButton cleanupAnalyzeButton;
    private javax.swing.JTextArea cleanupResultsTextArea;
    private javax.swing.JButton cleanupViewResultsButton;
    private javax.swing.JLabel coverArtCheck;
    private javax.swing.JLabel currentDirLabel;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteSelectedButton;
    private javax.swing.JCheckBox everythingElseCheckBox;
    private javax.swing.JLabel filenameCheck;
    private javax.swing.JCheckBox flacCheckBox;
    private javax.swing.JCheckBox imagesCheckBox;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JCheckBox mp3asdCheckBox;
    private javax.swing.JButton nextFolderButton;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JButton previousFolderButton;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JCheckBox wavCheckBox;
    private javax.swing.JCheckBox windowsCheckBox;
    private javax.swing.JCheckBox zipCheckBox;
    // End of variables declaration//GEN-END:variables
}
