/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moose;

import com.mpatric.mp3agic.ID3v2;
import com.mpatric.mp3agic.ID3v24Tag;
import com.mpatric.mp3agic.InvalidDataException;
import com.mpatric.mp3agic.Mp3File;
import com.mpatric.mp3agic.UnsupportedTagException;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author pat
 */
public class AuditFrame extends javax.swing.JFrame {

    //Frame frame;
    int auditCount;
    ArrayList<File> albums = new ArrayList<>();
    File auditFolder;
    File currentDir;
    boolean auditInProgress = false;

    /**
     * Creates new form AuditFrame
     */
    public AuditFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        auditPanel = new javax.swing.JPanel();
        previousFolderButton = new javax.swing.JButton();
        nextFolderButton = new javax.swing.JButton();
        ID3TagCheck = new javax.swing.JLabel();
        filenameCheck = new javax.swing.JLabel();
        coverArtCheck = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        chooseFolderButton = new javax.swing.JButton();
        pathLabel = new javax.swing.JLabel();
        currentDirLabel = new javax.swing.JLabel();
        cleanupPanel = new javax.swing.JPanel();
        analyzeButton = new javax.swing.JButton();
        clearResultsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTextArea = new javax.swing.JTextArea();
        zipCheckBox = new javax.swing.JCheckBox();
        mp3asdCheckBox = new javax.swing.JCheckBox();
        wavCheckBox = new javax.swing.JCheckBox();
        flacCheckBox = new javax.swing.JCheckBox();
        imagesCheckBox = new javax.swing.JCheckBox();
        everythingElseCheckBox = new javax.swing.JCheckBox();
        deleteAllButton = new javax.swing.JButton();
        deleteSelectedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Audit Music");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        previousFolderButton.setText("<-- Previous");
        previousFolderButton.setEnabled(false);
        previousFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousFolderButtonActionPerformed(evt);
            }
        });

        nextFolderButton.setText("Save & Next -->");
        nextFolderButton.setEnabled(false);
        nextFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFolderButtonActionPerformed(evt);
            }
        });

        ID3TagCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        filenameCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        coverArtCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        label3.setText("Every file has necessary ID3Tag information");
        label3.setEnabled(false);

        label4.setText("Filenames all match standard");
        label4.setEnabled(false);

        label5.setText("Has cover art associated with the folder");
        label5.setEnabled(false);

        label2.setText("Current Folder:");
        label2.setEnabled(false);

        startButton.setText("Start Audit");
        startButton.setEnabled(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop Audit");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        label1.setText("Audit Folder:");
        label1.setEnabled(false);

        chooseFolderButton.setText("Choose Folder...");
        chooseFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFolderButtonActionPerformed(evt);
            }
        });

        pathLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        pathLabel.setText(" ");
        pathLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        currentDirLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        currentDirLabel.setText(" ");
        currentDirLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        currentDirLabel.setMaximumSize(new java.awt.Dimension(17, 339));
        currentDirLabel.setMinimumSize(new java.awt.Dimension(17, 339));
        currentDirLabel.setPreferredSize(new java.awt.Dimension(17, 339));

        javax.swing.GroupLayout auditPanelLayout = new javax.swing.GroupLayout(auditPanel);
        auditPanel.setLayout(auditPanelLayout);
        auditPanelLayout.setHorizontalGroup(
            auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(auditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentDirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(previousFolderButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(coverArtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(ID3TagCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(filenameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chooseFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(auditPanelLayout.createSequentialGroup()
                        .addComponent(label2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auditPanelLayout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        auditPanelLayout.setVerticalGroup(
            auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chooseFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, auditPanelLayout.createSequentialGroup()
                        .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID3TagCheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filenameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coverArtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(auditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabbedPane.addTab("Audit", auditPanel);

        analyzeButton.setText("Perform Analysis");
        analyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButtonActionPerformed(evt);
            }
        });

        clearResultsButton.setText("Clear");
        clearResultsButton.setEnabled(false);
        clearResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearResultsButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Results:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");

        resultsTextArea.setEditable(false);
        resultsTextArea.setColumns(20);
        resultsTextArea.setRows(5);
        resultsTextArea.setWrapStyleWord(true);
        resultsTextArea.setEnabled(false);
        jScrollPane1.setViewportView(resultsTextArea);

        zipCheckBox.setText(".zip");
        zipCheckBox.setEnabled(false);

        mp3asdCheckBox.setText(".mp3.asd");
        mp3asdCheckBox.setEnabled(false);

        wavCheckBox.setText(".wav");
        wavCheckBox.setEnabled(false);

        flacCheckBox.setText(".flac");
        flacCheckBox.setEnabled(false);

        imagesCheckBox.setText("Images (Excludes cover art images, i.e. cover.*)");
        imagesCheckBox.setEnabled(false);

        everythingElseCheckBox.setText("Everything Else");
        everythingElseCheckBox.setEnabled(false);

        deleteAllButton.setText("Delete All");
        deleteAllButton.setEnabled(false);
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });

        deleteSelectedButton.setText("Delete Selected");
        deleteSelectedButton.setEnabled(false);
        deleteSelectedButton.setMaximumSize(new java.awt.Dimension(97, 40));
        deleteSelectedButton.setMinimumSize(new java.awt.Dimension(97, 40));
        deleteSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cleanupPanelLayout = new javax.swing.GroupLayout(cleanupPanel);
        cleanupPanel.setLayout(cleanupPanelLayout);
        cleanupPanelLayout.setHorizontalGroup(
            cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cleanupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cleanupPanelLayout.createSequentialGroup()
                        .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(analyzeButton)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearResultsButton))
                    .addComponent(imagesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(cleanupPanelLayout.createSequentialGroup()
                        .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cleanupPanelLayout.createSequentialGroup()
                                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(flacCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(wavCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mp3asdCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(zipCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deleteSelectedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(cleanupPanelLayout.createSequentialGroup()
                        .addComponent(everythingElseCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        cleanupPanelLayout.setVerticalGroup(
            cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cleanupPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cleanupPanelLayout.createSequentialGroup()
                        .addComponent(analyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(clearResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cleanupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cleanupPanelLayout.createSequentialGroup()
                        .addComponent(deleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteSelectedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57))
                    .addGroup(cleanupPanelLayout.createSequentialGroup()
                        .addComponent(zipCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mp3asdCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wavCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(flacCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(everythingElseCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagesCheckBox)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Cleanup", cleanupPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFolderButtonActionPerformed
        nextAuditFolder();
    }//GEN-LAST:event_nextFolderButtonActionPerformed

    private void previousFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousFolderButtonActionPerformed
        previousAuditFolder();
    }//GEN-LAST:event_previousFolderButtonActionPerformed

    private void chooseFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFolderButtonActionPerformed
        chooseFolder();
        startButton.setEnabled(true);
        importAlbums();
    }//GEN-LAST:event_chooseFolderButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        auditInProgress = true;
        startButton.setEnabled(false);
        stopButton.setEnabled(true);
        nextFolderButton.setEnabled(true);
        previousFolderButton.setEnabled(true);
        startAudit();
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        stopAudit();
        resetAuditFrame();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Main.frame.dispose();
        Main.frame = new Frame();
        Main.launchFrame();
    }//GEN-LAST:event_formWindowClosed

    private void clearResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearResultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearResultsButtonActionPerformed

    private void analyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analyzeButtonActionPerformed

    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    private void deleteSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteSelectedButtonActionPerformed

    public void refreshAuditFrame() {
        label3.setEnabled(true);
        label4.setEnabled(true);
        label5.setEnabled(true);
        if(checkID3Tags()) {
            ID3TagCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/check2.png")));
        } else {
            ID3TagCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/error.png")));
        }
        if(checkFilenames()) {
            filenameCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/check2.png")));
        } else {
            filenameCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/error.png")));
        }
        if(checkFolderCover()) {
            coverArtCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/check2.png")));
        } else {
            coverArtCheck.setIcon(new ImageIcon(this.getClass().getResource("/resources/error.png")));
        }
        currentDirLabel.setText(currentDir.getPath());
    }

    public void chooseFolder() {

        // use a filechooser to open the folder full of stuff
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setAcceptAllFileFilterUsed(false);

        // result of filechoosing
        int returnVal = fc.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            auditFolder = fc.getSelectedFile();
            label1.setEnabled(true);
            pathLabel.setText(auditFolder.getPath());
        }
    }

    public void importAlbums() {
        ArrayList<File> allFiles = new ArrayList<>();
        allFiles = Main.frame.listFiles(auditFolder, allFiles);
        for (File file : allFiles) {
            if (file.getName().endsWith(".mp3")) {
                File a = file.getParentFile();

                // folder is a multi-disk album
                if (a.getName().equals("CD1") || a.getName().equals("CD2")) {
                    a = a.getParentFile();
                }
                if (!albums.contains(a)) {
                    albums.add(a);
                }
            }
        }
        Collections.sort(albums, (File o1, File o2) -> {
            String filename1 = o1.getPath().replace("/Users/pat/Music/Library/", "");
            String filename2 = o2.getPath().replace("/Users/pat/Music/Library/", "");
            return filename1.compareToIgnoreCase(filename2);
        });
    }

    public void startAudit() {

        if (checkForExisitingAudit()) {
            Object[] options = new Object[]{"Cancel", "Start New", "Continue"};
            int returnVal = JOptionPane.showOptionDialog(this, "An exisiting audit is in process, do you want to continue?", "Existing audit found", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, options, null);
            switch (returnVal) {
                case 2:     // continue
                    continueAudit();
                    break;
                case 1:     // start a new one
                    newAudit();
                    break;
                default:
                    // do nothing
                    break;
            }
        } else {
            newAudit();
        }

    }

    public void newAudit() {
        clearDoneFiles();
        auditCount = 0;
        currentDir = albums.get(auditCount);
        refreshAuditFrame();
        Main.frame.dispose();
        Main.frame = new Frame(albums.get(auditCount));
        Main.launchFrame();
    }

    public void continueAudit() {
        auditCount = getNextAlbum();
        currentDir = albums.get(auditCount);
        refreshAuditFrame();
        Main.frame.dispose();
        Main.frame = new Frame(currentDir);
        Main.launchFrame();
    }

    public void nextAuditFolder() {
        if (!checkIfDone(albums.get(auditCount))) {
            setDone(albums.get(auditCount));
        }
        auditCount++;
        Main.frame.saveAll();
        if (auditCount < albums.size()) {
            currentDir = albums.get(auditCount);
            refreshAuditFrame();

            Main.frame.dispose();
            Main.frame = new Frame(currentDir);
            Main.launchFrame();
            this.requestFocus();
        } else {
            // audit is done
            finishAudit();
        }
    }

    public void previousAuditFolder() {
        if (!checkIfDone(albums.get(auditCount))) {
            setDone(albums.get(auditCount));
        }

        if (auditCount <= 0) {
            // do nothing
        } else {
            auditCount--;
            currentDir = albums.get(auditCount);
            refreshAuditFrame();
            Main.frame.dispose();
            Main.frame = new Frame(currentDir);
            Main.launchFrame();
            this.requestFocus();
        }
    }

    public void stopAudit() {
        albums.clear();
        Main.frame.dispose();
        Main.frame = new Frame();
        Main.launchFrame();
    }

    public void finishAudit() {
        albums.clear();
        auditCount = 0;
        auditInProgress = false;
        
        // launch a blank mainframe
        Main.frame.dispose();
        Main.frame = new Frame();
        Main.launchFrame();
        
        // reset the audit frame
        resetAuditFrame();
        
        // show that audit is done
        JOptionPane.showMessageDialog(null, "Audit is complete!", "Audit Completed", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void resetAuditFrame() {
        label1.setEnabled(false);
        label2.setEnabled(false);
        label3.setEnabled(false);
        label4.setEnabled(false);
        label5.setEnabled(false);
        ID3TagCheck.setIcon(null);
        filenameCheck.setIcon(null);
        coverArtCheck.setIcon(null);
        previousFolderButton.setEnabled(false);
        nextFolderButton.setEnabled(false);
        currentDirLabel.setText("");
        pathLabel.setText("");
        startButton.setEnabled(false);
        stopButton.setEnabled(false);
        this.requestFocus();
    }

    public boolean checkForExisitingAudit() {
        return albums.stream().anyMatch((album) -> (containsFile(album)));
    }

    public boolean containsFile(File dir) {
        File[] filesInAlbum = dir.listFiles();
        for (File file : filesInAlbum) {
            if (file.getName().equals("done")) {
                return true;
            }
        }
        return false;
    }

    public void setDone(File dir) {
        String path = dir.getPath() + "/done";
        File done = new File(path);
        try {
            done.createNewFile();
        } catch (IOException ex) {
            Main.logger.logError("Error creating done file for auditing in folder: " + path, ex);
        }
    }

    public boolean checkIfDone(File dir) {
        File[] files = dir.listFiles();
        for (File file : files) {
            if (file.getName().equals("done")) {
                return true;
            }
        }
        return false;
    }

    public int getNextAlbum() {
        for (File album : albums) {
            if (!checkIfDone(album)) {
                return albums.indexOf(album);
            }
        }
        return -1;
    }

    public void clearDoneFiles() {
        albums.stream().filter((album) -> (containsFile(album))).map((album) -> album.listFiles()).forEachOrdered((files) -> {
            for (File file : files) {
                if (file.getName().equals("done")) {
                    file.delete();
                }
            }
        });
    }

    private boolean checkFolderCover() {

        if (!auditInProgress) {
            return false;
        }

        File[] files = currentDir.listFiles();
        for (File file : files) {
            if (file.getName().startsWith("cover")) {
                return true;
            }
        }
        return false;
    }

    private boolean checkFilenames() {

        if (!auditInProgress) {
            return false;
        }

        ArrayList<File> files = new ArrayList<>();
        files = Main.frame.listFiles(currentDir, files);

        String regex = "\\d\\d ((.)*)";

        for (File file : files) {
            if (file.getName().endsWith(".mp3")) {
                if (!file.getName().matches(regex) && !isLabel(file)) {
                    return false;
                }
            }
        }
        return true;
    }

    private boolean checkID3Tags() {

        if (!auditInProgress) {
            return false;
        }

        ArrayList<File> files = new ArrayList<>();
        files = Main.frame.listFiles(currentDir, files);

        for (File file : files) {

            if (file.getName().endsWith(".mp3")) {

                // mp3agic Mp3File object, used for the id3tags
                Mp3File mp3file;
                try {
                    // create the mp3file from the file's path
                    mp3file = new Mp3File(file.getAbsolutePath());

                    // if the mp3file doesn't have an id3tag, create one
                    if (!mp3file.hasId3v2Tag()) {
                        ID3v2 tag = new ID3v24Tag();
                        mp3file.setId3v2Tag(tag);
                    }
                } catch (IOException | UnsupportedTagException | InvalidDataException ex) {
                    // things borked
                    mp3file = null;
                }

                // get the id3v2 info
                String title = mp3file.getId3v2Tag().getTitle();
                String artist = mp3file.getId3v2Tag().getArtist();
                String album = mp3file.getId3v2Tag().getAlbum();
                String albumartist = mp3file.getId3v2Tag().getAlbumArtist();
                String genre = mp3file.getId3v2Tag().getGenreDescription();
                String year = mp3file.getId3v2Tag().getYear();
                String track = mp3file.getId3v2Tag().getTrack();
                String disk = mp3file.getId3v2Tag().getPartOfSet();
                byte[] artwork_bytes = mp3file.getId3v2Tag().getAlbumImage();

                if (isLabel(currentDir)) {
                    if (title == null
                            || artist == null
                            || album == null
                            || albumartist == null
                            || genre == null
                            || artwork_bytes == null) {
                        return false;
                    }
                } else {
                    if (title == null
                            || artist == null
                            || album == null
                            || albumartist == null
                            || genre == null
                            || year == null
                            || track == null
                            || disk == null
                            || artwork_bytes == null) {
                        return false;
                    }
                }
            }
        }
        return true;
    }

    public boolean isLabel(File dir) {
        String path = dir.getPath();
        return path.contains("/Genres/");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new AuditFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID3TagCheck;
    private javax.swing.JButton analyzeButton;
    private javax.swing.JPanel auditPanel;
    private javax.swing.JButton chooseFolderButton;
    private javax.swing.JPanel cleanupPanel;
    private javax.swing.JButton clearResultsButton;
    private javax.swing.JLabel coverArtCheck;
    private javax.swing.JLabel currentDirLabel;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteSelectedButton;
    private javax.swing.JCheckBox everythingElseCheckBox;
    private javax.swing.JLabel filenameCheck;
    private javax.swing.JCheckBox flacCheckBox;
    private javax.swing.JCheckBox imagesCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JCheckBox mp3asdCheckBox;
    private javax.swing.JButton nextFolderButton;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JButton previousFolderButton;
    private javax.swing.JTextArea resultsTextArea;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JCheckBox wavCheckBox;
    private javax.swing.JCheckBox zipCheckBox;
    // End of variables declaration//GEN-END:variables
}
